x-coolify:
  mode: raw
services:
  redis:
    image: 'redis:alpine'
    restart: always
    volumes:
      - '/mailu/redis:/data'
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
  front:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}'
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-front
    expose:
      - "80"
    ports:
      - '127.0.0.1:25:25'
      - '127.0.0.1:465:465'
      - '127.0.0.1:587:587'
      - '127.0.0.1:110:110'
      - '127.0.0.1:995:995'
      - '127.0.0.1:143:143'
      - '127.0.0.1:993:993'
      - '127.0.0.1:4190:4190'
    networks:
      - default
    volumes:
      - '/mailu/certs:/certs'
      - '/mailu/overrides/nginx:/overrides:ro'
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailu-front.rule=Host(`mail.egyflow.cloud`)
      - traefik.http.routers.mailu-front.entrypoints=websecure
      - traefik.http.routers.mailu-front.tls=true
      - traefik.http.services.mailu-front.loadbalancer.server.port=80
  resolver:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}'
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254
  admin:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}'
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - '/mailu/data:/data'
      - '/mailu/dkim:/dkim'
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailu-admin.rule=Host(`admin.egyflow.cloud`)
      - traefik.http.routers.mailu-admin.entrypoints=websecure
      - traefik.http.routers.mailu-admin.tls=true
      - traefik.http.services.mailu-admin.loadbalancer.server.port=80
  imap:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}'
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - '/mailu/mail:/mail'
      - '/mailu/overrides/dovecot:/overrides:ro'
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
  smtp:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}'
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - '/mailu/mailqueue:/queue'
      - '/mailu/overrides/postfix:/overrides:ro'
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
  oletools:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2024.06}'
    hostname: oletools
    logging:
      driver: journald
      options:
        tag: mailu-oletools
    restart: always
    networks:
      - oletools
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
  antispam:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}'
    hostname: antispam
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - oletools
    volumes:
      - '/mailu/filter:/var/lib/rspamd'
      - '/mailu/overrides/rspamd:/overrides:ro'
    depends_on:
      - front
      - redis
      - oletools
      - resolver
    dns:
      - 192.168.203.254
  webmail:
    image: '${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}'
    restart: always
    env_file: .env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - '/mailu/webmail:/data'
      - '/mailu/overrides/roundcube:/overrides:ro'
    networks:
      - webmail
    depends_on:
      - front
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailu-webmail.rule=Host(`webmail.egyflow.cloud`)
      - traefik.http.routers.mailu-webmail.entrypoints=websecure
      - traefik.http.routers.mailu-webmail.tls=true
      - traefik.http.services.mailu-webmail.loadbalancer.server.port=80
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.203.0/24
  webmail:
    driver: bridge
  oletools:
    driver: bridge
    internal: true
